# Generated by Django 2.2.6 on 2019-10-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('job', models.CharField(max_length=50, serialize=False)),
                ('Description', models.TextField()),
                ('HourlyRate', models.CharField(max_length=50)),
                ('MaxHoursPerDay', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                 ('machinecode', models.CharField(max_length=50, serialize=False)),
                ('Descriptions', models.TextField()),
                ('HourlyRate', models.CharField(max_length=50)),
                ('MaxHoursPerDay', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sitecode', models.CharField(max_length=50)),
                ('nameofcontracter', models.TextField()),
                ('Totalhrs', models.CharField(max_length=50)),
                ('Totalamount', models.CharField(max_length=50)),
            ],
        ),
    ]
