# Generated by Django 2.2.6 on 2019-10-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='State',
            field=models.CharField(default='Review', max_length=50),
        ),
    ]
