# Generated by Django 2.2.6 on 2019-10-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administer', '0002_timecard_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machinecode',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
