# Generated by Django 2.2.6 on 2019-10-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administer', '0003_auto_20191018_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machinecode',
            field=models.CharField(max_length=50),
        ),
    ]
