# Generated by Django 2.2.6 on 2019-10-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertimecardmachine',
            name='MachineCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administer.Machine'),
        ),
    ]
